sudo: required
services:
  - docker

before_install:
  - docker build -t bahaeddinoz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bahaeddinoz/react-test npm test

after_success:
  - docker build -t bahaeddinoz/multi-client ./client
  - docker build -t bahaeddinoz/multi-nginx ./nginx
  - docker build -t bahaeddinoz/multi-server ./server
  - docker build -t bahaeddinoz/multi-worker ./worker

  # Login to Docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub

  - docker push bahaeddinoz/multi-client
  - docker push bahaeddinoz/multi-nginx
  - docker push bahaeddinoz/multi-server
  - docker push bahaeddinoz/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-263139023809
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWSACCESSKEY
  secret_access_key: $AWSSECRETKEY
